apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  selector:
    matchLabels:
      nfs: "primary"
  resources:
    requests:
      storage: 1Mi
